/**
 * Shared test vectors and demo scenarios for the contrast engine.
 *
 * Both the server test suite and the client explanation view import these, so
 * there is exactly one set of inputs and expected values. Expected numbers
 * are hand-computed against the WCAG definitions (sRGB EOTF, relative
 * luminance, (L1+0.05)/(L2+0.05)) — they are not generated by the engine
 * itself.
 */
import type {ContrastRequest, ContrastResult} from './contrast';

export interface Scenario {
  id: string;
  label: string;
  description: string;
  request: ContrastRequest;
}

/** 50% black text over a sampled white pixel (background-image area). */
const sampledWhite: Scenario = {
  id: 'sampled-white',
  label: '半透明黑字 / 已采样白底',
  description: '背景图采样色为白，文字 rgba(0,0,0,.5)。',
  request: {
    foreground: {
      name: 'body text',
      color: {rgb: [0, 0, 0], alpha: 0.5},
    },
    backgrounds: [
      {
        name: 'image sample #fff',
        kind: 'sample',
        color: {rgb: [1, 1, 1]},
      },
    ],
    threshold: 4.5,
  },
};

/** Two translucent paint layers over an opaque page background. */
const multiLayer: Scenario = {
  id: 'multi-layer',
  label: '多层半透明背景',
  description: '页面白底 + rgba(0,0,0,.5) 蒙层，黑字。',
  request: {
    foreground: {name: 'body text', color: {rgb: [0, 0, 0]}},
    backgrounds: [
      {name: 'page', color: {rgb: [1, 1, 1]}},
      {name: 'scrim', kind: 'paint', color: {rgb: [0, 0, 0], alpha: 0.5}},
    ],
    threshold: 4.5,
  },
};

/** Backdrop not sampled — answer must be a range. */
const unknownBase: Scenario = {
  id: 'unknown-base',
  label: '未知底色（背景图未采样）',
  description: '黑字下方是未采样的背景图，只能给出 1..21 的范围。',
  request: {
    foreground: {name: 'body text', color: {rgb: [0, 0, 0]}},
    backgrounds: [{name: 'unspecified image', kind: 'unknown'}],
    threshold: 4.5,
  },
};

/** Fully transparent text: pixel is the backdrop unchanged. */
const transparentText: Scenario = {
  id: 'transparent-text',
  label: 'alpha=0 文字',
  description: '完全透明的黑字等于不存在，对比度恒为 1。',
  request: {
    foreground: {name: 'invisible text', color: {rgb: [0, 0, 0], alpha: 0}},
    backgrounds: [{name: 'page', kind: 'sample', color: {rgb: [1, 1, 1]}}],
  },
};

/** Opaque text, alpha boundary on the other side. */
const opaqueText: Scenario = {
  id: 'opaque-text',
  label: 'alpha=1 文字（已知采样色）',
  description: '#000 文字压在采样色 #fff 上，21:1。',
  request: {
    foreground: {name: 'body text', color: {rgb: [0, 0, 0], alpha: 1}},
    backgrounds: [{name: 'image sample', kind: 'sample', color: {rgb: [1, 1, 1]}}],
  },
};

/** Display-P3 primary red: out of sRGB gamut, must be downgraded. */
const wideGamutP3: Scenario = {
  id: 'wide-gamut-p3',
  label: '宽色域 display-p3 降级',
  description: 'P3 红降级为 sRGB 红（蓝通道被钳到 0），约 3.998:1。',
  request: {
    foreground: {
      name: 'p3 red text',
      color: {rgb: [1, 0, 0], space: 'display-p3'},
    },
    backgrounds: [{name: 'page', color: {rgb: [1, 1, 1]}}],
  },
};

/** ProPhoto primary green: much wider gamut, heavy clamp. */
const wideGamutProPhoto: Scenario = {
  id: 'wide-gamut-prophoto',
  label: '宽色域 ProPhoto 降级',
  description: 'ProPhoto 绿经 D50→D65 矩阵降级到 sRGB 绿。',
  request: {
    foreground: {
      name: 'prophoto green text',
      color: {rgb: [0, 1, 0], space: 'prophoto-rgb'},
    },
    backgrounds: [{name: 'page', color: {rgb: [1, 1, 1]}}],
  },
};

/**
 * Unrounded ratio is just under 4.5, but it displays as "4.50:1".
 * Verdict must come from the unrounded value (fail).
 */
const roundingBoundary: Scenario = {
  id: 'rounding-boundary',
  label: '四舍五入边界 4.4995',
  description: '原始值 4.4995 显示为 4.50:1，但判定必须失败。',
  request: {
    foreground: {name: 'body text', color: {rgb: [0, 0, 0]}},
    backgrounds: [
      {
        name: 'gray backdrop',
        // encoded sRGB gray whose linear luminance is 4.4995·0.05 − 0.05
        color: {rgb: [0.45530026501800464, 0.45530026501800464, 0.45530026501800464]},
      },
    ],
    threshold: 4.5,
  },
};

/** Translucent white text over an unspecified image: range 1..11. */
const translucentOverUnknown: Scenario = {
  id: 'translucent-unknown',
  label: '半透明白字 / 未知底',
  description: 'rgba(255,255,255,.5) 压在未采样背景上：白底上糊成白(1:1)，黑底上 11:1。',
  request: {
    foreground: {name: 'body text', color: {rgb: [1, 1, 1], alpha: 0.5}},
    backgrounds: [{name: 'unspecified image', kind: 'unknown'}],
    threshold: 4.5,
  },
};

/** Translucent BLACK text over an unspecified image: range 1..1.909 (never passes). */
const darkTextOverUnknown: Scenario = {
  id: 'dark-text-unknown',
  label: '半透明黑字 / 未知底（恒失败）',
  description: 'rgba(0,0,0,.5) 压在未采样背景上：即便黑底也只有 1:1，白底 1.91:1。',
  request: {
    foreground: {name: 'body text', color: {rgb: [0, 0, 0], alpha: 0.5}},
    backgrounds: [{name: 'unspecified image', kind: 'unknown'}],
    threshold: 4.5,
  },
};

/** 8-bit encoded input exercises the 0..255 path. */
const encoded255: Scenario = {
  id: 'encoded-255',
  label: '8 位 srgb-255 输入',
  description: '#3a3a3a(58) 采样色 + 黑字，约 1.8462:1。',
  request: {
    foreground: {name: 'body text', color: {rgb: [0, 0, 0]}},
    backgrounds: [{name: 'sample', kind: 'sample', color: {rgb: [58, 58, 58], space: 'srgb-255'}}],
  },
};

export const scenarios: Scenario[] = [
  opaqueText,
  sampledWhite,
  multiLayer,
  unknownBase,
  transparentText,
  wideGamutP3,
  wideGamutProPhoto,
  roundingBoundary,
  translucentOverUnknown,
  darkTextOverUnknown,
  encoded255,
];

/* ------------------------------------------------------------------ */
/* Hard-coded expected results. Tight tolerances on the numeric paths.  */
/* ------------------------------------------------------------------ */

export interface ExpectedContrast {
  scenarioId: string;
  kind: 'exact' | 'range';
  exact?: number;
  min?: number;
  max?: number;
  pass: boolean | 'partial';
  /** Expected color-source facts the engine must report. */
  facts?: {
    foregroundDowngraded?: boolean;
    foregroundChannels?: ContrastResult['foreground']['channels'];
    foregroundAlphaState?: ContrastResult['foreground']['alphaState'];
    traceSteps?: number;
  };
}

export const expectedResults: ExpectedContrast[] = [
  {
    scenarioId: 'opaque-text',
    kind: 'exact',
    exact: 21,
    pass: true,
    facts: {foregroundAlphaState: 'opaque', traceSteps: 2},
  },
  {
    scenarioId: 'sampled-white',
    kind: 'exact',
    exact: 1.909090909090909,
    pass: false,
    facts: {foregroundAlphaState: 'translucent', traceSteps: 2},
  },
  {
    scenarioId: 'multi-layer',
    kind: 'exact',
    // half-black scrim over white = linear .5 -> ratio (0.5+.05)/.05
    exact: 11,
    pass: true,
    facts: {traceSteps: 3},
  },
  {
    scenarioId: 'unknown-base',
    kind: 'range',
    min: 1,
    max: 21,
    pass: 'partial',
    // Unknown base contributes no known layer to the trace; foreground only.
    facts: {traceSteps: 1},
  },
  {
    scenarioId: 'transparent-text',
    kind: 'exact',
    exact: 1,
    pass: false,
    facts: {foregroundAlphaState: 'transparent', traceSteps: 2},
  },
  {
    scenarioId: 'wide-gamut-p3',
    kind: 'exact',
    exact: 3.9984767707539985,
    pass: false,
    facts: {
      foregroundDowngraded: true,
      // P3 red linear (1,0,0) maps outside sRGB on all three channels:
      // red ~1.225 clamps high, green/blue negative clamp low.
      foregroundChannels: ['clamped-high', 'clamped-low', 'clamped-low'],
      traceSteps: 2,
    },
  },
  {
    scenarioId: 'wide-gamut-prophoto',
    kind: 'exact',
    exact: 1.3721902770517513,
    pass: false,
    facts: {foregroundDowngraded: true, traceSteps: 2},
  },
  {
    scenarioId: 'rounding-boundary',
    kind: 'exact',
    exact: 4.4995,
    pass: false,
    facts: {traceSteps: 2},
  },
  {
    scenarioId: 'translucent-unknown',
    kind: 'range',
    min: 1,
    max: 11,
    pass: 'partial',
  },
  {
    scenarioId: 'dark-text-unknown',
    kind: 'range',
    min: 1,
    max: 1.909090909090909,
    pass: false,
  },
  {
    scenarioId: 'encoded-255',
    kind: 'exact',
    exact: 1.8462282124161935,
    pass: false,
  },
];

export function scenarioById(id: string): Scenario {
  const found = scenarios.find(s => s.id === id);
  if (!found) throw new Error(`unknown scenario ${id}`);
  return found;
}

export function expectedFor(id: string): ExpectedContrast {
  const found = expectedResults.find(e => e.scenarioId === id);
  if (!found) throw new Error(`no expected result for ${id}`);
  return found;
}
